### ISSUE TITLE
list tidders are unessessarily long 

### ISSUE THREAD

**Issue by petedaws** [reidgould/tiddlywiki-dropboard#2]
I have a board with a list containing a single tidder. The list has a long scrollbar at the bottom even though the tiddler is mostly empty. I would have thought that the width of the tiddler in the list would match the width of the list.

![dropboard-issue](https://user-images.githubusercontent.com/1418586/32816341-de627f9c-ca03-11e7-82c1-e11603733385.png)

**Comment by reidgould** [comment]
hmm, that's not good. I haven't seen this one before, can you isolate the issue more? For example, does the list only become too wide with that one card or is it happening with any card? Or does that card cause any list it is in to become too wide? 

If you export & share the tiddlers involved (or even the whole wiki if it doesn't have sensitive info) I'll take a look.

**Comment by petedaws** [comment]
It was happening with all tiddlers in all lists. However. Now that I am looking at this again, I'm not seeing that behaviour. In fact now it looks fine and I can't reproduce. Possibly in a dodgy state after a resizing of the firefox window. I'll keep an eye out for it.

**Comment by reidgould** [comment]
Ok. I'm going to close this issue for now, but if you find a way to reproduce please do reopen. Thanks!

**Comment by reidgould** [comment]
Fixed in release [1.0.2](https://github.com/reidgould/tiddlywiki-dropboard/releases/tag/1.0.2) by resolution in issue #4.
