### ISSUE TITLE
Table Card Overlay in TiddlyDesktop

### ISSUE THREAD

**Issue by weidmanngabriel** [reidgould/tiddlywiki-dropboard#3]
I got my Dropboard-Tiddlywiki in the TiddlyDesktop program.

This is the usual case: No problem at all as long as there is space down there:

![no_error](https://user-images.githubusercontent.com/6526439/32993366-3e9bfe50-cd57-11e7-8bf7-623e20cf3dbb.PNG)

But if I got to many cards inside the board, they'll make this:

![error](https://user-images.githubusercontent.com/6526439/32993368-3ebc8346-cd57-11e7-8fd8-22936bc68a0f.PNG)

This isn't really comfortable to work with :(

PS: In the firefox and edge browsers it works well, but I don't want to use the browser, because of Saving restrictions.

**Comment by reidgould** [comment]
Oh no, I can't believe I missed this! I definitely want to support TiddlyDesktop so I'll be looking into this as soon as I can. Thanks for reporting.

**Comment by reidgould** [comment]
Fixed in release [1.0.1](https://github.com/reidgould/tiddlywiki-dropboard/releases/tag/1.0.1) which is now live in the user guide. Let me know if you have any other problems!

**Comment by weidmanngabriel** [comment]
Perfect. Now it works! 👍 
Thanks for this amazing plugin. I like it more than Trello, because it's offline and I can include it into version control.
