### ISSUE TITLE
Drag n drop from top bar breaks when sidebarlayout switched to fixed-fluid

### ISSUE THREAD

**Issue by mortuosplango** [reidgould/tiddlywiki-dropboard#4]
Hey,

If the sidebar layout is set to fixed story - fluid sidebar (Control Panel --> Appearance --> Theme Tweaks --> Sidebar layout, $:/themes/tiddlywiki/vanilla/options/sidebarlayout), the "+" button drops the whole image (or subtiddler?) when dragged and the whole drag n drop area changes appearance.

If the sidebar layout is set to fluid story - fixed sidebar, the board works as expected. 

BTW, thanks for writing this great plugin!

**Comment by reidgould** [comment]
This looks like it's the issue we couldn't figure out in #2, I'll look into this as soon as I get the chance. Thanks for reporting!

**Comment by reidgould** [comment]
Fixed in release [1.0.2](https://github.com/reidgould/tiddlywiki-dropboard/releases/tag/1.0.2). Thanks for sharing the details needed to solve this one, @mortuosplango !
