### ISSUE TITLE
Can't create a new list of cards

### ISSUE THREAD

**Issue by Guitlle** [reidgould/tiddlywiki-dropboard#6]
It took me a while to understand I had to drag the New Tiddler button to the kanban area to create the first list. Then, to add a new list of cards I figured I could clone the first list I made, or I could add the category of the board title so it shows. This is awesome. I just think it should be able to create a list by dragging the new tiddler button and hovering the area between lists

**Comment by TimSoethout** [comment]
I'm experiencing similar problems. Thanks for the clone tip. It was the only way I could find how to make more columns.

But now my cloned lists are the full width... Is it possible to limit the width?

**Comment by TimSoethout** [comment]
Ah it seems to be in the readme: "You can drop any tiddler link onto [...] the << And >> Drop Areas".

**Comment by reidgould** [comment]
Thanks for the feedback. If Dropboard ever gets a version 2, a better interface for list creation and arrangement is a priority. For now, this seems resolved so I'll close the issue. Happy drag and dropping!
